language: rust

jobs:
    fast_finish: true
    include:
        - rust: stable
          script:
            - ifconfig
            - cargo build
            - tests/test_nomangle.sh
          # cache ~/.cargo explicitly so that ./target isn't cached
          cache:
              directories:
                  - $HOME/.cargo
