language: rust
sudo: required

jobs:
    fast_finish: true
    include:
        - rust: stable
          script:
            - ifconfig
            - cargo build
            - tests/test-nomangle.sh
          before_cache:
            - cargo install cargo-sweep
            - cargo sweep -i
          cache: cargo
