language: rust

jobs:
    fast_finish: true
    include:
        - rust: stable
          script:
            - ifconfig
            - cargo build
            - sudo tests/test-nomangle.sh
          before_cache:
            - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
            - cargo install cargo-sweep
            - cargo sweep -i
          cache: cargo
